# Use postgres/example user/password credentials
version: "3.1"

services:
  postgresql:
    container_name: washington-park
    image: mdillon/postgis
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin4:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

volumes:
    pgadmin:
